CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable GPIO
CONFIG_GPIO=y

# Enable STM32 LTDC Custom support
CONFIG_DISPLAY=y
CONFIG_MIPI_DSI=y
CONFIG_STM32_LTDC_ARGB8888=y
CONFIG_MIPI_DSI_STM32_CUSTOM=y
CONFIG_DISPLAY_INIT_PRIORITY=85
CONFIG_MIPI_DSI_INIT_PRIORITY=86
CONFIG_DISPLAY_HX8379C_INIT_PRIORITY=87

# Main thread configuration
CONFIG_MAIN_STACK_SIZE=8192

# Memory configuration
CONFIG_HEAP_MEM_POOL_SIZE=32768

# Enable printf functionality
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# Enable logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y

# System configuration
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=160000000

# Build configuration
CONFIG_BUILD_OUTPUT_HEX=y

# CONFIG_ARM_MPU=n

# CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_MIPI_DSI_LOG_LEVEL_DBG=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y

# Debugging and optimization settings
CONFIG_DEBUG_OPTIMIZATIONS=y
